# Results and evaluation of reproducibility

```{=html}
<!-- 
- Were you able to replicate all or part of the study methods? Why / why not?
- Were you able to reproduce all or part of the published results? Why / why not?
- Please attach any relevant results as an appendix. -->
```
## Data processing

The data we obtained and used to reproduce the results from Ripley et al. were in a structured format and easy to work with. For some studies, data were extracted that were not needed to reproduce the results such as sham conditions. Respective entries were easy to identify using comments within the data. Data pre-processing included renaming of variables and recoding of some entries (e.g. '50% male' in the sex variable was converted to 'Both'). In cases in which cohort sizes were given as ranges, we used the lowest number as the sample size. As defined in the methods of the original review, <!--how to we call the thing we are replicating?--> we divided the control groups by the number of experimental arms if the ratio was higher than 1. In three cases within two studies, this procedure would have ended in cohort sizes lower than one. The authors defined here that in those cases "Where experimental arms outnumbered control group animals, the review team made decisions on the most relevant experimental arms, in consultation with stroke experts." Although specified here, we were not able to identify, based on the data, a) how 'most relevant' was defined and b) which comparison was finally included. The answer to b) was found in the supplemental file in which the rows excluded from analysis were marked red but we found no indication for a) and what led to exclusion.

## Main analyses

We found that overall, groups that received RIC showed significantly reduced infarct volume compared to control groups (SMD = `r main_smd`, 95% CI [`r main_lower`; `r main_upper`], *I*^2^ = `r main_i2`%). This result supports the findings and conclusions of the main meta-analysis reported in Ripley and colleagues (SMD = -2.19, 95% CI [-2.48; -1.91], *I*^2^ = 74%). Although the interpretation of the direction of the overall effect does not change, we observed a notable deviation in average effect size compared to the original review amounting to a `r es_change`% difference. A difference of this magnitude highlights the challenge of computationally reproducing the main finding of the study we set out to replicate.

<!-- ## Subgroup analyses -->

<!-- The subgroup analyses showed that efficacy of RIC differed significantly between male and female animals (), as well as between timing of conditioning (), however there was no significant difference of stroke model and type of RIC in the intervention's efficacy. These analyses support the findings of Ripley and colleagues (Fig 3 of original review). -->


