---
title: "Evaluating the computational reproducibility of a systematic review on neuroprotective intervention in animal models of stroke"
# author: "Maria Economou & Torsten Rackoll"
bibliography:
  - "`r here::here('docs/repro_challenge_SR-SAVI_2024.bib')`"
  - "`r here::here('docs/R_references.bib')`"

csl: "`r here::here('docs/apa_short_authors.csl')`"

output:
  bookdown::word_document2: 
    reference_docx: CAMARADES_repro_challenge_report_template.docx
    
# output:
#   word_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
library("here")
flextable::set_flextable_defaults(font.family = "TimesNewRoman")
source(here::here("scripts","03_Small_data.R"))
```

<br> <br>

Maria Economou^1^, Torsten Rackoll^1^

<br>

^1^ BIH Quest Center for Responsible Research, Charité Universitätsmedizin

<br>

<!-- Introduction -->

```{r, 'include-intro', child='01_Introduction.Rmd', eval=T}
```

<!-- Methods -->

```{r, 'include-method', child='02_Methods.Rmd', eval=T}
```

<!-- Results -->

```{r, 'include-results', child='03_Results.Rmd', eval=T}
```

<!-- Discussion -->

```{r, 'include-discussion', child='04_Discussion.Rmd', eval=T}
```

\newpage

# Appendix

## References {.unnumbered}

```{=tex}
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
```
::: {#refs custom-style="Bibliography"}
:::

```{=tex}
\endgroup
```
